<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/22 19:16:18

return array(
'propel' => new sfPropelDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'jobeet',
  'password' => 'jobeet',
  'name' => 'propel',
)),);
